# ============================================================
# SE1020 Movie Platform ? REST API Configuration (SOA)
# ============================================================

# Server
server.port=7000
server.servlet.context-path=/

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://admin:Admin1234@movierental.x7dnnb1.mongodb.net/cinevault?retryWrites=true&w=majority&appName=MovieRental


# Embedded Tomcat
server.tomcat.max-threads=200
server.tomcat.connection-timeout=5000

# CORS ? Angular dev server
app.cors.allowed-origins=http://localhost:4200

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# Seed data into MongoDB on first run
app.seed.enabled=true